service: FaunaLogsToDatadog  # Replace with your desired service name

provider:
  name: aws
  runtime: nodejs18.x  # Adjust as needed

functions:
  myLambdaFunction:
    handler: index.handler  # Assuming your handler is in index.js and named 'handler'
    events:
      - schedule:
          rate: rate(1 hour)  # Replace with your desired schedule expression, currently set to run once every hour
plugins:
  - serverless-dotenv-plugin
  - serverless-offline
custom:
  dotenv:
    path: .env  # Specify the path to your .env file containing environment variables
